@@include('files/regular.js', {})
@@include('files/functions.js', {})
@@include('files/script.js', {})
@@include('files/animations-lottie.js', {})
@@include('files/forms.js', {})
@@include('files/scroll.js', {})
@@include('files/sliders.js', {})